Script started on Tue 24 Aug 2021 09:31:06 PM CDT
[?1034hbash-4.2$ exit[1Pgdb./simple [5Pexit./simple 

Enter in 10 numbers (follow with a space after each number and press enter when finished):
>> 0 1 2 3 4 5 6 7 8 9

~ Finding the sum of the square roots inside of array... Σ√([ 0 1 2 3 4 5 6 7 8 9 ])
>> The average of the square roots in array: 1.930600




***End of Program***

bash-4.2$ gdb [K
[?1034hGNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-120.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
(gdb) file simple
Reading symbols from /home/u3/mto0006/comp-3500/projects/project1/task3/simple...done.
(gdb) r
Starting program: /home/u3/mto0006/comp-3500/projects/project1/task3/simple 

Enter in 10 numbers (follow with a space after each number and press enter when finished):
>> 0 1 2 3 4 5 6 7 8 9

~ Finding the sum of the square roots inside of array... Σ√([ 0 1 2 3 4 5 6 7 8 9 ])
>> The average of the square roots in array: 1.930600




***End of Program***

[Inferior 1 (process 15012) exited normally]
Missing separate debuginfos, use: debuginfo-install glibc-2.17-324.el7_9.x86_64
(gdb) break main
Breakpoint 1 at 0x40063f: file simple.c, line 86.
(gdb) r
Starting program: /home/u3/mto0006/comp-3500/projects/project1/task3/simple 

Breakpoint 1, main () at simple.c:86
86	    int array[ARRAY_SIZE]; 
(gdb) n
89	    printf("%s", enter10Numbers());
(gdb) s
enter10Numbers () at simple.c:50
50	    return "\nEnter in 10 numbers (follow with a space after each number and press enter when finished):\n>> ";
(gdb) c
Continuing.

Enter in 10 numbers (follow with a space after each number and press enter when finished):
>> 0 1 2 3 4 5 6 7 89  9

~ Finding the sum of the square roots inside of array... Σ√([ 0 1 2 3 4 5 6 7 8 9 ])
>> The average of the square roots in array: 1.930600




***End of Program***

[Inferior 1 (process 15044) exited normally]
(gdb) infor br[K[K[K[K break
Num     Type           Disp Enb Address            What
1       breakpoint     keep y   0x000000000040063f in main at simple.c:86
	breakpoint already hit 1 time
(gdb) del 1
(gdb) break sqrt
Breakpoint 2 at 0x7ffff7aff690
(gdb) r
Starting program: /home/u3/mto0006/comp-3500/projects/project1/task3/simple 

Enter in 10 numbers (follow with a space after each number and press enter when finished):
>> 0 1 2 3 4 5 6 7 8 9


Breakpoint 2, 0x00007ffff7aff690 in sqrt () from /lib64/libm.so.6
(gdb) n
Single stepping until exit from function sqrt,
which has no line number information.
main () at simple.c:108
108	    for (loop = 0; loop < ARRAY_SIZE; loop++)
(gdb) s
111	        sum += sqrt(array[loop]);
(gdb) c
Continuing.

Breakpoint 2, 0x00007ffff7aff690 in sqrt () from /lib64/libm.so.6
(gdb) info break
Num     Type           Disp Enb Address            What
2       breakpoint     keep y   0x00007ffff7aff690 <sqrt>
	breakpoint already hit 2 times
(gdb) del 2
(gdb) info regsi[K[Ksi[K[Kisters
rax            0x1	1
rbx            0x10	16
rcx            0x295d	10589
rdx            0x1	1
rsi            0x4009c3	4196803
rdi            0x0	0
rbp            0x7fffffffe160	0x7fffffffe160
rsp            0x7fffffffe108	0x7fffffffe108
r8             0x0	0
r9             0x7ffff77582cd	140737345061581
r10            0x7fffffffdcd0	140737488346320
r11            0x7ffff7aff690	140737348892304
r12            0x7fffffffe140	140737488347456
r13            0x7fffffffe240	140737488347712
r14            0x0	0
r15            0x0	0
rip            0x7ffff7aff690	0x7ffff7aff690 <sqrt>
eflags         0x293	[ CF AF SF IF ]
cs             0x33	51
ss             0x2b	43
ds             0x0	0
es             0x0	0
fs             0x0	0
gs             0x0	0
(gdb) q
A debugging session is active.

	Inferior 1 [process 15067] will be killed.

Quit anyway? (y or n) y
bash-4.2$ exit
exit

Script done on Tue 24 Aug 2021 09:32:47 PM CDT
